/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion_tutorias.vistas;

/**
 *
 * @author Luis Salgado
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {
FrmInsertarAmbito obj=new FrmInsertarAmbito();
        //obj.setVisible(true);
        //dispose();
    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_inserta = new javax.swing.JMenuItem();
        menu_modificar = new javax.swing.JMenuItem();
        menu_eliminar = new javax.swing.JMenuItem();
        menu_buscar = new javax.swing.JMenuItem();
        menu_listar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menu_insertar = new javax.swing.JMenuItem();
        menu_modificar_m = new javax.swing.JMenuItem();
        menu_eliminar_m = new javax.swing.JMenuItem();
        menu_buscar_m = new javax.swing.JMenuItem();
        menu_listar_m = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menu_insertar_e = new javax.swing.JMenuItem();
        menu_modificar_e = new javax.swing.JMenuItem();
        menu_eliminar_e = new javax.swing.JMenuItem();
        menu_buscar_e = new javax.swing.JMenuItem();
        menu_listar_e = new javax.swing.JMenuItem();
        Facultad = new javax.swing.JMenu();
        menu_insertar_f = new javax.swing.JMenuItem();
        menu_modificar_f = new javax.swing.JMenuItem();
        menu_eliminar_f = new javax.swing.JMenuItem();
        menu_buscar_f = new javax.swing.JMenuItem();
        menu_listar_f = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menu_insertar_p = new javax.swing.JMenuItem();
        menu_modificar_p = new javax.swing.JMenuItem();
        menu_eliminar_p = new javax.swing.JMenuItem();
        menu_buscar_p = new javax.swing.JMenuItem();
        menu_listar_p = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menu_insertar_n = new javax.swing.JMenuItem();
        menu_modificar_n = new javax.swing.JMenuItem();
        menu_eliminar_n = new javax.swing.JMenuItem();
        menu_busca_n = new javax.swing.JMenuItem();
        menu_listar_n = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menu_insertar_esc = new javax.swing.JMenuItem();
        menu_modificar_esc = new javax.swing.JMenuItem();
        menu_eliminar_esc = new javax.swing.JMenuItem();
        menu_buscar_esc = new javax.swing.JMenuItem();
        menu_listar_esc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacion_tutorias/imagenes_siget/6.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
        );

        jMenu1.setBackground(new java.awt.Color(0, 0, 153));
        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("MingLiU-ExtB", 2, 18)); // NOI18N

        jMenuItem1.setText("Ingresar");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 153));
        jMenu2.setText("Ambito");
        jMenu2.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        menu_inserta.setText("Insertar");
        menu_inserta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertaActionPerformed(evt);
            }
        });
        jMenu2.add(menu_inserta);

        menu_modificar.setText("Modificar");
        menu_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_modificarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_modificar);

        menu_eliminar.setText("Eliminar");
        menu_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_eliminarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_eliminar);

        menu_buscar.setText("Buscar");
        menu_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buscarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_buscar);

        menu_listar.setText("Listar");
        menu_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_listarActionPerformed(evt);
            }
        });
        jMenu2.add(menu_listar);

        jMenuBar1.add(jMenu2);

        jMenu3.setBackground(new java.awt.Color(0, 0, 153));
        jMenu3.setText("Modalidad");
        jMenu3.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar.setText("Insertar");
        menu_insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertarActionPerformed(evt);
            }
        });
        jMenu3.add(menu_insertar);

        menu_modificar_m.setText("Modificar");
        jMenu3.add(menu_modificar_m);

        menu_eliminar_m.setText("Eliminar");
        menu_eliminar_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_eliminar_mActionPerformed(evt);
            }
        });
        jMenu3.add(menu_eliminar_m);

        menu_buscar_m.setText("Buscar");
        menu_buscar_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_buscar_mActionPerformed(evt);
            }
        });
        jMenu3.add(menu_buscar_m);

        menu_listar_m.setText("Listar");
        jMenu3.add(menu_listar_m);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 0, 153));
        jMenu4.setText("Estudiante");
        jMenu4.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar_e.setText("Insertar");
        menu_insertar_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertar_eActionPerformed(evt);
            }
        });
        jMenu4.add(menu_insertar_e);

        menu_modificar_e.setText("Modificar");
        jMenu4.add(menu_modificar_e);

        menu_eliminar_e.setText("Eliminar");
        jMenu4.add(menu_eliminar_e);

        menu_buscar_e.setText("Buscar");
        jMenu4.add(menu_buscar_e);

        menu_listar_e.setText("Listar");
        jMenu4.add(menu_listar_e);

        jMenuBar1.add(jMenu4);

        Facultad.setBackground(new java.awt.Color(0, 0, 153));
        Facultad.setText("Facultad");
        Facultad.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar_f.setText("Insertar");
        menu_insertar_f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertar_fActionPerformed(evt);
            }
        });
        Facultad.add(menu_insertar_f);

        menu_modificar_f.setText("Modificar");
        Facultad.add(menu_modificar_f);

        menu_eliminar_f.setText("Eliminar");
        Facultad.add(menu_eliminar_f);

        menu_buscar_f.setText("Buscar");
        Facultad.add(menu_buscar_f);

        menu_listar_f.setText("Listar");
        Facultad.add(menu_listar_f);

        jMenuBar1.add(Facultad);

        jMenu8.setBackground(new java.awt.Color(0, 0, 153));
        jMenu8.setText("Periodo");
        jMenu8.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar_p.setText("Insertar");
        menu_insertar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertar_pActionPerformed(evt);
            }
        });
        jMenu8.add(menu_insertar_p);

        menu_modificar_p.setText("Modificar");
        jMenu8.add(menu_modificar_p);

        menu_eliminar_p.setText("Eliminar");
        menu_eliminar_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_eliminar_pActionPerformed(evt);
            }
        });
        jMenu8.add(menu_eliminar_p);

        menu_buscar_p.setText("Buscar");
        jMenu8.add(menu_buscar_p);

        menu_listar_p.setText("Listar");
        jMenu8.add(menu_listar_p);

        jMenuBar1.add(jMenu8);

        jMenu7.setBackground(new java.awt.Color(0, 0, 153));
        jMenu7.setText("Nivel");
        jMenu7.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar_n.setText("Insertar");
        menu_insertar_n.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertar_nActionPerformed(evt);
            }
        });
        jMenu7.add(menu_insertar_n);

        menu_modificar_n.setText("Modificar");
        jMenu7.add(menu_modificar_n);

        menu_eliminar_n.setText("Eliminar");
        jMenu7.add(menu_eliminar_n);

        menu_busca_n.setText("Buscar");
        jMenu7.add(menu_busca_n);

        menu_listar_n.setText("Listar");
        jMenu7.add(menu_listar_n);

        jMenuBar1.add(jMenu7);

        jMenu6.setBackground(new java.awt.Color(0, 0, 153));
        jMenu6.setText("Escuela");
        jMenu6.setFont(new java.awt.Font("MingLiU_HKSCS", 2, 18)); // NOI18N

        menu_insertar_esc.setText("Insertar");
        menu_insertar_esc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_insertar_escActionPerformed(evt);
            }
        });
        jMenu6.add(menu_insertar_esc);

        menu_modificar_esc.setText("Modificar");
        jMenu6.add(menu_modificar_esc);

        menu_eliminar_esc.setText("Eliminar");
        jMenu6.add(menu_eliminar_esc);

        menu_buscar_esc.setText("Buscar");
        jMenu6.add(menu_buscar_esc);

        menu_listar_esc.setText("Listar");
        jMenu6.add(menu_listar_esc);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_insertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertaActionPerformed
        new FrmInsertarAmbito().setVisible(true);
    }//GEN-LAST:event_menu_insertaActionPerformed

    private void menu_insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertarActionPerformed
        new FrmInsertarModalidad().setVisible(true);
    }//GEN-LAST:event_menu_insertarActionPerformed

    private void menu_insertar_eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertar_eActionPerformed
        new FrmInsertarEstudiante().setVisible(true);
    }//GEN-LAST:event_menu_insertar_eActionPerformed

    private void menu_eliminar_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_eliminar_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_eliminar_mActionPerformed

    private void menu_eliminar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_eliminar_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_eliminar_pActionPerformed

    private void menu_insertar_fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertar_fActionPerformed
       new FrmInsertarFacultad().setVisible(true);
    }//GEN-LAST:event_menu_insertar_fActionPerformed

    private void menu_insertar_escActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertar_escActionPerformed
       new FrmInsertarEscuela().setVisible(true);
    }//GEN-LAST:event_menu_insertar_escActionPerformed

    private void menu_insertar_nActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertar_nActionPerformed
       new FrmInsertarNivel().setVisible(true);
    }//GEN-LAST:event_menu_insertar_nActionPerformed

    private void menu_insertar_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_insertar_pActionPerformed
        new FrmInsertarPeriodo().setVisible(true);
    }//GEN-LAST:event_menu_insertar_pActionPerformed

    private void menu_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buscarActionPerformed
        new FrmBuscarAmbito().setVisible(true);
    }//GEN-LAST:event_menu_buscarActionPerformed

    private void menu_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_modificarActionPerformed
        new FrmModificarAmbito().setVisible(true);
    }//GEN-LAST:event_menu_modificarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void menu_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_eliminarActionPerformed
        new FrmEliminarAmbito().setVisible(true);
    }//GEN-LAST:event_menu_eliminarActionPerformed

    private void menu_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_listarActionPerformed
        new FrmListarAmbito().setVisible(true);
    }//GEN-LAST:event_menu_listarActionPerformed

    private void menu_buscar_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_buscar_mActionPerformed
        new FrmBuscarModalidad().setVisible(true);
    }//GEN-LAST:event_menu_buscar_mActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Facultad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menu_busca_n;
    private javax.swing.JMenuItem menu_buscar;
    private javax.swing.JMenuItem menu_buscar_e;
    private javax.swing.JMenuItem menu_buscar_esc;
    private javax.swing.JMenuItem menu_buscar_f;
    private javax.swing.JMenuItem menu_buscar_m;
    private javax.swing.JMenuItem menu_buscar_p;
    private javax.swing.JMenuItem menu_eliminar;
    private javax.swing.JMenuItem menu_eliminar_e;
    private javax.swing.JMenuItem menu_eliminar_esc;
    private javax.swing.JMenuItem menu_eliminar_f;
    private javax.swing.JMenuItem menu_eliminar_m;
    private javax.swing.JMenuItem menu_eliminar_n;
    private javax.swing.JMenuItem menu_eliminar_p;
    private javax.swing.JMenuItem menu_inserta;
    private javax.swing.JMenuItem menu_insertar;
    private javax.swing.JMenuItem menu_insertar_e;
    private javax.swing.JMenuItem menu_insertar_esc;
    private javax.swing.JMenuItem menu_insertar_f;
    private javax.swing.JMenuItem menu_insertar_n;
    private javax.swing.JMenuItem menu_insertar_p;
    private javax.swing.JMenuItem menu_listar;
    private javax.swing.JMenuItem menu_listar_e;
    private javax.swing.JMenuItem menu_listar_esc;
    private javax.swing.JMenuItem menu_listar_f;
    private javax.swing.JMenuItem menu_listar_m;
    private javax.swing.JMenuItem menu_listar_n;
    private javax.swing.JMenuItem menu_listar_p;
    private javax.swing.JMenuItem menu_modificar;
    private javax.swing.JMenuItem menu_modificar_e;
    private javax.swing.JMenuItem menu_modificar_esc;
    private javax.swing.JMenuItem menu_modificar_f;
    private javax.swing.JMenuItem menu_modificar_m;
    private javax.swing.JMenuItem menu_modificar_n;
    private javax.swing.JMenuItem menu_modificar_p;
    // End of variables declaration//GEN-END:variables
}